"use client";

import Button from "@/components/ui/Button";
import Modal from "@/components/ui/Modal";
import { ErrorNote } from "@/components/ui/Panel";
import type { ChangeResult } from "@/lib/types";

/**
 * Shows the SQL a save would run, generated by a dry run on the server and
 * rolled back, so what the user approves is exactly what executes.
 */
export default function ChangeScript({
  open,
  preview,
  error,
  busy,
  onCancel,
  onApply,
}: {
  open: boolean;
  preview: ChangeResult | null;
  error: string | null;
  busy: boolean;
  onCancel: () => void;
  onApply: () => void;
}) {
  return (
    <Modal
      open={open}
      title="Review changes"
      description={
        preview
          ? `${preview.inserts} insert, ${preview.updates} update, ${preview.deletes} delete statements.`
          : "Checking your changes against the database."
      }
      onClose={onCancel}
      footer={
        <>
          <Button variant="ghost" size="sm" onClick={onCancel} disabled={busy}>
            Cancel
          </Button>
          <Button
            size="sm"
            onClick={onApply}
            disabled={busy || !preview || preview.script.length === 0}
          >
            {busy ? "Applying…" : "Apply changes"}
          </Button>
        </>
      }
    >
      {error && <ErrorNote>{error}</ErrorNote>}

      {preview && preview.script.length > 0 && (
        <pre className="max-h-[320px] overflow-auto rounded-lg border border-line bg-surface-2 p-3 font-mono text-caption leading-relaxed text-fg">
          {preview.script.join("\n")}
        </pre>
      )}

      {preview && !error && (
        <p className="mt-3 text-caption text-fg-subtle">
          Everything runs in one transaction. If any statement fails, nothing is applied.
        </p>
      )}
    </Modal>
  );
}
